/**
 * A file `init` WRITES has to compile in the project it was written into.
 *
 * Reported from the field against 2.14.0 (#998): `init` generates `src/reticle-dev.ts` guarded on
 * `import.meta.env.DEV`, whose TYPE ships in `vite/client`. An app whose tsconfig pins
 * `"types": ["node", "react", "react-dom"]` — or that simply has no `vite-env.d.ts` — never pulls
 * that in, so `tsc` answers `TS2339: Property 'env' does not exist on type 'ImportMeta'` and a
 * `"build": "tsc && vite build"` goes from green to red purely because somebody ran onboarding.
 * The reporter's own repair was to edit their tsconfig, which is a project file `init` should not
 * need them to change to run a dev-only tool.
 *
 * Nothing else here can see it. The generated file is a STRING in this package, never parsed; every
 * app under `apps/` already carries `vite/client` through its own `vite-env.d.ts`, so it is exactly
 * the shape that cannot reproduce it; and the install gate BOOTS the app it scaffolds rather than
 * typechecking it. So this runs the real compiler over the real generated bytes, in a project
 * carrying the one property the report is about.
 */

import { describe, expect, it } from 'vitest';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { basename, dirname, join } from 'node:path';
import ts from 'typescript';
import { craDevModuleFile, craDevModulePath } from './cra.js';
import { VITE_DEV_MODULE_PATH, viteDevModuleFile } from './snippets.js';
import { buildPlan, StepStatus, type PlanInput } from '@/plan/plan.js';
import { Framework, PackageManager, UiLibrary, type Detection } from '@/detect/detect.js';

/**
 * The smallest tsconfig a real Vite + TypeScript app can have, with the one thing the report is
 * about left out: nothing here pulls in `vite/client`.
 *
 * `types: []` rather than the reporter's `["node", "react", "react-dom"]` — those three would have
 * to be installed in the temp project to resolve at all, and none of them is what decides this.
 * What decides it is that `vite/client` is not among them, which an empty list states exactly.
 *
 * `allowJs` + `checkJs: false` is how a bundler treats a `.js` file: parsed, not type-checked. It is
 * here so the SAME compiler answers the JavaScript half of the question — a TypeScript-only
 * construct in a `.js` file is a grammar error (TS8006/TS8010), which is what "still plain
 * JavaScript" means mechanically.
 */
const HOST_COMPILER_OPTIONS: ts.CompilerOptions = {
  target: ts.ScriptTarget.ES2022,
  module: ts.ModuleKind.ESNext,
  moduleResolution: ts.ModuleResolutionKind.Bundler,
  lib: ['lib.es2023.d.ts', 'lib.dom.d.ts'],
  strict: true,
  noEmit: true,
  skipLibCheck: true,
  types: [],
  allowJs: true,
  checkJs: false,
};

/**
 * The installed SDK, as much of it as module resolution needs.
 *
 * A stand-in rather than the real package: what is under test is `import.meta`, not the adapter's
 * own types, and pointing at `adapters/framework/react` would drag React's type tree and a build
 * artifact into a unit test. Both specifiers are here because `sdkImport` picks between them — a
 * Vue or Svelte app is generated against `@reticlehq/browser`.
 */
const SDK_PACKAGES: readonly string[] = ['@reticlehq/react', '@reticlehq/browser'];

function sdkStub(): Record<string, string> {
  const files: Record<string, string> = {};
  for (const name of SDK_PACKAGES) {
    files[`node_modules/${name}/package.json`] =
      `{ "name": "${name}", "version": "0.0.0", "types": "index.d.ts" }\n`;
    files[`node_modules/${name}/index.d.ts`] =
      'export declare function registerCapabilities(capabilities: {\n' +
      '  testids: readonly string[];\n' +
      '  signals: readonly string[];\n' +
      '  stores: readonly string[];\n' +
      '}): void;\n' +
      'export declare function registerStore(key: string, store: unknown): void;\n';
  }
  return files;
}

/**
 * The relevant declarations from `vite/client`. The catch-all index uses `unknown`; only the
 * named DEV and env members decide the declaration-merging behavior tested here.
 *
 * Reproduced rather than resolved because `vite` is not a dependency of this package, and the half
 * of it that decides this question is these two interfaces.
 *
 * It is also the reason the declaration we generate is shaped the way it is. `DEV` is not `readonly`
 * there, and `env` is — so a stricter-looking copy on our side is not a harmless duplicate, it is
 * `TS2687: All declarations of 'DEV' must have identical modifiers`. That would trade the reported
 * red build for a red build in every project that DOES have `vite/client`, which is most of them.
 */
const VITE_CLIENT_TYPES = `interface ImportMetaEnv extends Record<string, unknown> {
  BASE_URL: string;
  MODE: string;
  DEV: boolean;
  PROD: boolean;
  SSR: boolean;
}

interface ImportMeta {
  url: string;
  readonly env: ImportMetaEnv;
}
`;

/** Where a project that HAS the Vite ambient types keeps them — this is create-vite's own file. */
const VITE_ENV_DTS_PATH = 'src/vite-env.d.ts';

function formatDiagnostic(diagnostic: ts.Diagnostic): string {
  const message = ts.flattenDiagnosticMessageText(diagnostic.messageText, ' ');
  const where = diagnostic.file === undefined ? '' : `${basename(diagnostic.file.fileName)}: `;
  return `${where}TS${String(diagnostic.code)}: ${message}`;
}

/**
 * Compile a whole throwaway project and return what the compiler said.
 *
 * Real files in a real temp directory, because module resolution is half the question: a stub
 * package has to be FOUND through `node_modules` the way the app's own install would be.
 */
function typecheck(files: Readonly<Record<string, string>>): readonly string[] {
  const root = mkdtempSync(join(tmpdir(), 'reticle-generated-types-'));
  try {
    for (const [relPath, content] of Object.entries(files)) {
      const absolute = join(root, relPath);
      mkdirSync(dirname(absolute), { recursive: true });
      writeFileSync(absolute, content, 'utf8');
    }
    const program = ts.createProgram({
      // Only the app's own sources are roots; `node_modules` is reached through resolution.
      rootNames: Object.keys(files)
        .filter((relPath) => relPath.startsWith('src/'))
        .map((relPath) => join(root, relPath)),
      options: HOST_COMPILER_OPTIONS,
    });
    return ts.getPreEmitDiagnostics(program).map(formatDiagnostic);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
}

/** The generated module as `init` writes it for a plain Vite + React app. */
const reactDevModule = (): string => viteDevModuleFile(['pay'], [], [], UiLibrary.REACT);

describe('the generated Vite dev module compiles in the project init writes it into', () => {
  it('typechecks where the tsconfig never pulls in vite/client', () => {
    expect(
      typecheck({ ...sdkStub(), [VITE_DEV_MODULE_PATH]: reactDevModule() }),
      'a project that runs `tsc` as part of its build must stay green after `reticle init`',
    ).toEqual([]);
  });

  it('typechecks for a Vue app too, where the module imports the sensor instead of the React kit', () => {
    expect(
      typecheck({
        ...sdkStub(),
        [VITE_DEV_MODULE_PATH]: viteDevModuleFile([], [], [], UiLibrary.VUE),
      }),
    ).toEqual([]);
  });

  it('typechecks with a store it wired from the app’s own source', () => {
    expect(
      typecheck({
        ...sdkStub(),
        'src/store.ts': 'export const useCart = { getState: (): unknown => ({}) };\n',
        [VITE_DEV_MODULE_PATH]: viteDevModuleFile(
          ['pay'],
          [],
          [{ key: 'cart', ident: 'useCart', importPath: './store' }],
          UiLibrary.REACT,
        ),
      }),
    ).toEqual([]);
  });

  it('still typechecks in a project that DOES have vite/client — the declaration merges, never collides', () => {
    expect(
      typecheck({
        ...sdkStub(),
        [VITE_ENV_DTS_PATH]: VITE_CLIENT_TYPES,
        [VITE_DEV_MODULE_PATH]: reactDevModule(),
      }),
      'a declaration of our own must not red-build the projects that were fine before',
    ).toEqual([]);
  });

  it('still typechecks beside a project’s own env augmentation, which is what create-vite tells people to write', () => {
    expect(
      typecheck({
        ...sdkStub(),
        [VITE_ENV_DTS_PATH]: `${VITE_CLIENT_TYPES}
interface ImportMetaEnv {
  readonly VITE_API_URL: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
`,
        [VITE_DEV_MODULE_PATH]: reactDevModule(),
      }),
    ).toEqual([]);
  });

  /**
   * The guard is the product here: Vite substitutes this exact member expression at build time, so
   * the block — and the SDK import inside it — is dead code a production build drops entirely.
   * Reaching for the type through a cast, an optional chain or a `globalThis` lookup would compile
   * just as well and silently ship the SDK to users.
   */
  it('keeps the literal guard Vite replaces at build time, so production still drops the block', () => {
    expect(reactDevModule()).toContain('if (import.meta.env.DEV) {');
  });

  /** A type-only fix: it reads the flag no extra times, and reaches for it no other way. */
  it('reads the flag exactly once, and through no runtime lookup', () => {
    const file = reactDevModule();
    const reads = file
      .split('\n')
      .filter((line) => !line.trim().startsWith('//') && line.includes('import.meta.env.DEV'));
    expect(reads).toHaveLength(1);
    expect(file).not.toContain('globalThis');
  });
});

/**
 * The other half of the report is that `init` should not need the user to change their project to
 * make its own output compile. The reporter's repair was an edit to `tsconfig.json`; a fix that
 * made `init` do that edit for them would be the same intrusion with better manners.
 */
describe('typing the generated module costs the project no other file', () => {
  const detection: Detection = {
    framework: Framework.VITE,
    uiLibrary: UiLibrary.REACT,
    typescript: true,
    reactMajor: 19,
    needsSourceMapping: true,
    packageManager: PackageManager.PNPM,
  };
  const planInput = (viteDevModuleExists: boolean): PlanInput => ({
    detection,
    claudeCli: false,
    mcpExists: true,
    viteConfig: {
      path: 'vite.config.ts',
      source:
        "import { defineConfig } from 'vite';\nexport default defineConfig({ plugins: [] });\n",
    },
    nextConfigFile: null,
    nextReticleDevExists: false,
    viteDevModuleExists,
    testids: ['pay'],
    options: { port: undefined, mcp: true, install: false },
  });

  it('writes the dev module and nothing else that belongs to the project', () => {
    const written = buildPlan(planInput(false))
      .steps.filter((s) => s.write !== undefined)
      .map((s) => s.write?.path);
    expect(written).toContain(VITE_DEV_MODULE_PATH);
    // The two files a types fix is tempting to reach for, and both are the project's, not ours.
    expect(written).not.toContain('tsconfig.json');
    expect(written).not.toContain('src/vite-env.d.ts');
  });

  it('carries the declaration in the file init actually plans to write', () => {
    const step = buildPlan(planInput(false)).steps.find(
      (s) => s.write?.path === VITE_DEV_MODULE_PATH,
    );
    expect(step?.write?.content).toContain('declare global');
    expect(step?.write?.content).toContain('if (import.meta.env.DEV) {');
  });

  /**
   * The no-write case, and a real limit on this fix: the dev module is the one generated file a
   * user is expected to EDIT, so `init` leaves an existing one alone. A project wired by an older
   * `init` therefore does not gain the declaration by re-running it — deleting the file first is
   * what does, and silently rewriting somebody's capabilities registrations to add types would be
   * a worse trade than the bug.
   */
  it('still refuses to touch a dev module the project already has', () => {
    const steps = buildPlan(planInput(true)).steps.filter((s) => s.target === VITE_DEV_MODULE_PATH);
    expect(steps.map((s) => s.status)).toEqual([StepStatus.ALREADY]);
    expect(steps.every((s) => s.write === undefined)).toBe(true);
  });
});

describe('the JavaScript module init writes for a JavaScript project stays JavaScript', () => {
  /**
   * The other `reticle-dev` generator. A CRA project with no tsconfig gets `src/reticle-dev.js`
   * (#675), and an ambient TypeScript block leaking into it would be a parse error in the one
   * project shape that cannot strip types — the same defect as #998 wearing the opposite sign.
   */
  it('emits no TypeScript-only syntax a .js file cannot carry', () => {
    const path = craDevModulePath(false);
    expect(path).toBe('src/reticle-dev.js');
    expect(
      typecheck({
        ...sdkStub(),
        [path]: craDevModuleFile(4400, 'proj-abc', { typescript: false, testids: ['pay'] }),
      }),
    ).toEqual([]);
  });

  it('leaves the TypeScript branch of that generator marked as TypeScript', () => {
    expect(craDevModulePath(true)).toBe('src/reticle-dev.ts');
    expect(craDevModuleFile(4400, 'proj-abc', { typescript: true })).toContain('export {};');
  });
});
