import { chromium } from 'playwright';
import os from 'node:os'; import path from 'node:path'; import nfs from 'node:fs';
import { start, TOOLS, BaselineStore, RecordingStore, FlowStore, ProjectStore, AnnotationStore, createNodeFileSystem } from '@syrin/iris-server';
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));
let pass=0,fail=0; const chk=(l,o,d='')=>{console.log(`   ${o?'✅':'❌'} ${l}${d?'  — '+d:''}`);o?pass++:fail++;};
const irisRoot=path.join(os.tmpdir(),`iris-p3b-${process.pid}`,'.iris');
const fsp=createNodeFileSystem(); const now=()=>Date.now(); const flows=new FlowStore(fsp,irisRoot,{now}); const project=new ProjectStore(fsp,irisRoot,{now});
const server=await start({port:4400,mcp:false});
const deps={sessions:server.bridge.sessions,baselines:new BaselineStore(),recordings:new RecordingStore(),flows,project,fs:fsp,irisRoot,now,annotations:new AnnotationStore()};
const T=(n,a={})=>TOOLS.find(t=>t.name===n).handler(deps,{sessionId:'next-smoke',...a});
const b=await chromium.launch({headless:true}); const p=await b.newPage();
await p.goto('http://localhost:3100/',{waitUntil:'networkidle'});
for(let i=0;i<200&&server.bridge.sessions.count()===0;i++) await sleep(50);
const refOf=async(by,v)=>{for(let i=0;i<30;i++){const r=(await T('iris_query',{by,value:v})).elements?.[0]?.ref;if(r)return r;await sleep(100);}throw new Error('nf '+v);};
console.log('\n=== M8 Stage B: self-healing rebind (real browser) ===');
await T('iris_record_start',{recordingName:'ht'});
await T('iris_act',{ref:await refOf('testid','add-task'),action:'click'});
await T('iris_record_stop',{recordingName:'ht'});
await T('iris_flow_save',{flowName:'ht'});
const file=path.join(irisRoot,'flows','ht.json');
// corrupt the testid
nfs.writeFileSync(file, nfs.readFileSync(file,'utf8').replaceAll('add-task','add-tassk'));
const bytesBefore=nfs.readFileSync(file,'utf8');
const proposeOnly=await T('iris_flow_heal',{flowName:'ht',apply:false});
chk('heal(apply:false) proposes a rebind but does NOT write', /add-task/.test(JSON.stringify(proposeOnly)) && nfs.readFileSync(file,'utf8')===bytesBefore, JSON.stringify(proposeOnly).slice(0,120));
const applied=await T('iris_flow_heal',{flowName:'ht',apply:true});
chk('heal(apply:true) rewrites the anchor back to add-task', nfs.readFileSync(file,'utf8').includes('add-task') && applied.applied===true, JSON.stringify(applied).slice(0,110));
const rep=await T('iris_flow_replay',{flowName:'ht'});
chk('replay is green again after self-heal', rep.status==='ok'||rep.ok!==false&&!rep.drift, JSON.stringify(rep).slice(0,90));
console.log(`\n${fail===0?'✅ M8 STAGE B SELF-HEAL VERIFIED':'❌ FAILED'} (${pass} passed, ${fail} failed)`);
await b.close(); await server.close(); nfs.rmSync(path.dirname(irisRoot),{recursive:true,force:true}); process.exit(fail===0?0:1);
